name: Sync LeetCode

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * *"  # runs daily at 03:00 UTC

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync LeetCode submissions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
